class Metier:

    def __init__(self, nom):
        self.nom = nom
        self.propriete = ''

#niveau1
sans_emploi = Metier("")
vagabond = Metier("")
mendiant = Metier("")
fille_de_joie = Metier("")
prisonnier = Metier("")
aventurier = Metier("")
serf = Metier("")
nomade = Metier("")
bandit = Metier("")
sauvage = Metier("")
esclave = Metier("")
criminel = Metier("")
etranger = Metier("")
domestique = Metier("")
pirate = Metier("")
corsaire = Metier("")
matelot = Metier("")
druide = Metier("")

#niveau2
paysan = Metier("")
cuisinier = Metier("")
marchand = Metier("")
moine = Metier("")
soldat = Metier("")
garde = Metier("")
forgeron = Metier("")
berger = Metier("")
ecuyer = Metier("")
page = Metier("")
tisserand = Metier("")
meunier = Metier("")
boulanger = Metier("")
aubergiste = Metier("")
herboriste = Metier("")
alchimiste = Metier("")
mage = Metier("")
inquisiteur = Metier("")
pretre = Metier("")
espion = Metier("")
tenancier = Metier("")
laboureur = Metier("")
citoyen = Metier("")
ouvrier = Metier("")
artisan_novice = Metier("")
artisan_apprenti = Metier("")
marin = Metier("")
geolier = Metier("")
milicien = Metier("")
diacre = Metier("")
seminariste = Metier("")
bourreau = Metier("")

#niveau3
medecin = Metier("")
avocat = Metier("")
officier_de_justice = Metier("")
hero = Metier("")
capitaine = Metier("")
officier = Metier("")
adjuvant = Metier("")
bailli = Metier("")
artisan_intermediaire = Metier("")
artisan_compagnon = Metier("")
artisan_expert = Metier("")
commerçant = Metier("")
bourgeois = Metier("")
chevalier = Metier("")
paladin = Metier("")
curé = Metier("")
scribe = Metier("")
pretre = Metier("")
tresorier = Metier("")

#niveau4
artisan_maitre = Metier("")
conseiller = Metier("")
delegue = Metier("")
noble = Metier("")
seigneur = Metier("")
vassal = Metier("")
baron = Metier("")
delegue = Metier("")
marquis = Metier("")
vicomte = Metier("")
vicaire = Metier("")
doyen = Metier("")

#niveau5
comte = Metier("")
duc = Metier("")
archiduc = Metier("")
intendant = Metier("")
ministre = Metier("")
eveque = Metier("")
abbe = Metier("")

#niveau5
roi = Metier("")
prince = Metier("")
patriarch = Metier("")
archeveque = Metier("")
cardinal = Metier("")
primat = Metier("")


#niveau6
empereur = Metier("")
pape = Metier("")
elu = Metier("")

#armee niv2
piquier = Metier("")
archer = Metier("")
spadassin = Metier("")
lancier = Metier("")
cavalier = Metier("")
ingenieur = Metier("")
arbaletrier = Metier("")
pistolier = Metier("")
hallebardier = Metier("")
mercenaire = Metier("")
milicien = Metier("")
dragoon = Metier("")
eclaireur = Metier("")
